version: "3.9"
services:
  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: taskops-nacos
    environment:
      MODE: standalone
      PREFER_HOST_MODE: hostname
      JVM_XMS: 256m
      JVM_XMX: 256m
    ports:
      - "8848:8848"

  mysql:
    image: mysql:8.0
    container_name: taskops-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: taskops-redis
    ports:
      - "6379:6379"

  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    container_name: taskops-auth
    environment:
      NACOS_ADDR: nacos:8848
      NACOS_NAMESPACE: public
      TASKOPS_DB_URL: jdbc:mysql://mysql:3306/internship_taskops?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
      TASKOPS_DB_USER: root
      TASKOPS_DB_PASS: root
      TASKOPS_REDIS_HOST: redis
      TASKOPS_REDIS_PORT: 6379
      TASKOPS_JWT_SECRET: 1234567890123456789012345678901234567890
      TASKOPS_JWT_EXPIRE: 86400000
    depends_on:
      - nacos
      - mysql
      - redis

  task-service:
    build:
      context: ../task-service
      dockerfile: Dockerfile
    container_name: taskops-task
    environment:
      NACOS_ADDR: nacos:8848
      NACOS_NAMESPACE: public
      TASKOPS_DB_URL: jdbc:mysql://mysql:3306/internship_taskops?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
      TASKOPS_DB_USER: root
      TASKOPS_DB_PASS: root
      TASKOPS_REDIS_HOST: redis
      TASKOPS_REDIS_PORT: 6379
    depends_on:
      - nacos
      - mysql
      - redis
      - auth-service

  admin-service:
    build:
      context: ../admin-service
      dockerfile: Dockerfile
    container_name: taskops-admin
    environment:
      NACOS_ADDR: nacos:8848
      NACOS_NAMESPACE: public
    depends_on:
      - nacos
      - auth-service
      - task-service

  gateway-service:
    build:
      context: ../gateway-service
      dockerfile: Dockerfile
    container_name: taskops-gateway
    environment:
      NACOS_ADDR: nacos:8848
      NACOS_NAMESPACE: public
      TASKOPS_JWT_SECRET: 1234567890123456789012345678901234567890
    depends_on:
      - nacos
      - auth-service
      - task-service
      - admin-service

  nginx:
    image: nginx:1.27-alpine
    container_name: taskops-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.docker.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/html:/usr/share/nginx/html:ro
      - ../nginx/certs:/etc/nginx/certs:ro
      - ../nginx/logs:/var/log/nginx
    depends_on:
      - gateway-service

