services:
  nacos:
    image: docker.m.daocloud.io/nacos/nacos-server:v2.3.2
    container_name: taskops-nacos
    environment:
      MODE: standalone
      PREFER_HOST_MODE: hostname
      JVM_XMS: 256m
      JVM_XMX: 256m
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"

  mysql:
    image: mysql:8.0.18
    container_name: taskops-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    ports:
      - "3307:3306"
    volumes:
      - /home/elias/springCloud/mysql-data:/var/lib/mysql

  redis:
    image: docker.m.daocloud.io/library/redis:7-alpine
    container_name: taskops-redis
    ports:
      - "6380:6379"

  rabbitmq:
    image: docker.m.daocloud.io/library/rabbitmq:3.13-management
    container_name: taskops-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
